version: "3.8"

services:
  db:
    image: mysql:latest
    container_name: workout_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: workout_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: streamlit_app
    restart: always
    depends_on:
      - db
    ports:
      - "8501:8501"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=yourpassword
      - DB_NAME=workout_db
    volumes:
      - .:/app
    command: ["streamlit", "run", "app.py"]

volumes:
  mysql_data:
